### ISSUE TITLE
Couchbase 7.1 rollout plan

### ISSUE THREAD

**Issue by jesseops** [PlexTrac/plextrac-manager-util#51]
**Phase 1 - upgrade path validation**
Use image ```plextrac/plextracdb:7.1.1-beta```

- [ ] Direct upgrade with existing database (6.5.1 -> 7.1.1)
- [ ] Restore backup from CB 6 to CB 7
- [ ] Downgrade from CB 7 to CB 6 - is this possible?
- [ ] Automated upgrade for rolling out to customers
  - [ ] test with DO droplet and verify upgrade steps in this env

**Phase 2 - QA of app with CB 7**

#### Platform Testing

- [ ] Parser Actions, Import of Scan Data, Import of Clients, Reports, Templates
- [ ] Permissions and user audit before and after DB change
- [ ] Runbooks validation all is functioning as expected
- [ ] Assessments and their function
- [ ] Dashboards and information displayed is still accurate

#### Infrastructure testing
- [ ] Run API test suite
- [ ] AB evaluate query performance using benchmark tools
- [ ] Evaluate memory performance/requirements

##### Questions to answer
* Does this destroy existing containers and/or volumes?
* What items are changed about Couchbase specifically?
* How is data (specifically backups) affected by this change? 
* Can we still restore from 6.5.1 backups?
* What is expected down time?
* Will this affect indexes or create a need for manual data massage like last upgrade?
* Are there any differences in tunneling the DB or the indexes inside? CSEs want to know this incase they are looking at data
* Any potential issues with a mix of CB 6 and CB 7 databases in prod during a staged rollout? This is likely mitigated by updating the internal envs first so we confirm deploys are compatible with CB 7, but we should be cautious about incompatibility with CB 6

**Phase 3 - Rollout**

- [ ] Implement new DB in CSE envs for testing
- [ ] Implement in all Internal envs for testing (like success.qa and edge.qa)
- [ ] Verify dev repos and tools are using new image for CB 7
- [ ] Implement in AE envs to increase use testing (perhaps a new demo env for them to test in?)
Depending on the results from this stage, we should consider pausing and letting these environments bake to help catch any unknown issues.

**Phase 3.1 - Rollout to production**
- [ ] Implement in hand picked customer instances with careful monitoring
- [ ] Implement in customer blocks with defined adjustment period to limit impact if something goes catastrophically wrong

**Comment by jesseops** [comment]
@mmorgan-pt @Michael-Burke is there a rough timeline available for each phase?

**Comment by mmorgan-pt** [comment]
Testing confirms that the upgrade path appears to be smooth, whether in place or a restored database. Issues arise if attempting to rollback the container version or if restoring a CB 7 backup to CB 6.

Plan for automation is to setup a saltstack docker compose override and target specific minions.
